### ISSUE TITLE
No support for topologySpreadConstraints or podAntiAffinity

### ISSUE THREAD

**Issue by daniel-laszlo** [launchdarkly/ld-relay-helm#43]
**Describe the bug**
LD relay is a critical component in our stack and we cannot allow it to be down even if there is a zone failure. We would like to define something like this in a deployment:
```
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
          {{- include "launchdarkly-relay.selectorLabels" . | nindent 12 }}
        maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
```
