### ISSUE TITLE
Releases prior to 3.3.0 no longer resolve

### ISSUE THREAD

**Issue by rperryng** [launchdarkly/ld-relay-helm#62]
**Describe the bug**
References to older chart versions no longer resolve

I noticed the `index.yaml` was recently completely re-built, and older releases now have a new URL like:

```
https://launchdarkly.github.io/ld-relay-helm/helm-repo/ld-relay-3.1.0.tgz
```

note the `/helm-repo/` component, which doesn't seem to exist in the repo itself.  These URLs don's resolve

but the newest release `3.3.0` has a URL like:

```
https://launchdarkly.github.io/ld-relay-helm/ld-relay-3.3.0.tgz
```

which works.

**To reproduce**
```yaml
# Chart.yaml
---
apiVersion: v2
name: launchdarkly-relay-proxy
description: |
  The LaunchDarkly Relay Proxy is a small Go application that runs on your own infrastructure. It connects to the
  LaunchDarkly streaming API and proxies that connection to clients within your organization's network.
type: application
version: 1.0.0
appVersion: '1.0.0'
dependencies:
  - name: ld-relay
    version: 3.1.0
    repository: https://launchdarkly.github.io/ld-relay-helm
```

```
$ helm repo add launch-darkly-relay https://launchdarkly.github.io/ld-relay-helm

$helm dependency build .                                                       
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "launch-darkly-relay" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading ld-relay from repo https://launchdarkly.github.io/ld-relay-helm
Save error occurred:  could not download https://launchdarkly.github.io/ld-relay-helm/helm-repo/ld-relay-3.1.0.tgz: failed to fetch https://launchdarkly.github.io/ld-relay-helm/helm-repo/ld-relay-3.1.0.tgz : 404 Not Found
Error: could not download https://launchdarkly.github.io/ld-relay-helm/helm-repo/ld-relay-3.1.0.tgz: failed to fetch https://launchdarkly.github.io/ld-relay-helm/helm-repo/ld-relay-3.1.0.tgz : 404 Not Found
```

**Expected behavior**
Expected old chart versions to be able to be resolved when listed as a dependency

**Logs**
If applicable, add any log output related to your problem.

**Helm chart version**
```
$ helm version  
version.BuildInfo{Version:"v3.11.1", GitCommit:"293b50c65d4d56187cd4e2f390f0ada46b4c4737", GitTreeState:"clean", GoVersion:"go1.19.5"}

```

**Relay proxy configuration, developer tools**
n/a

**Additional context**
n/a
